service:
  clusterIP: 10.43.0.1 # use a static IP because k8s DNS does NOT work for this service

persistence:
  enabled: true

  ## Existing Persistent Volume Claim
  ## This should be used with persistence.enabled=true
  ## If defined, an existing volume claim will be used, instead
  ## of creating a new one. i.e. volume definition:
  ## persistentVolumeClaim:
  ##   claimName: {{ tpl .Values.persistence.existingClaim . }}
  existingClaim: "usb-pvc"

  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #storageClass: "-"

storageClass:
  create: false # do NOT create a new storage class

rbac:
  create: true

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: 
  hdd: enabled

tolerations: []

affinity: {}
