service:
  type: ClusterIP
ingress:
  enabled: true
  className: traefik
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: acmeresolver
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-stripprefix-middleware@kubernetescrd
  hosts:
    - host: yelpyourself.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - yelpyourself.com
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: jellyfin
          operator: In
          values:
          - "enabled"
persistence:
  config:
    enabled: true
    existingClaim: 'jellyfin-config-usb'
    accessMode: ReadWriteMany
    size: 1Gi
    storageClass: 'jellyfin-config-sc'
  media:
    enabled: true
    existingClaim: 'jellyfin-data-usb'
    type: pvc
    accessMode: ReadWriteMany
    size: 1Ti
    storageClass: 'jellyfin-data-sc'
