apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-data-nvme-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/nvme/data"
    server: 192.168.68.71
    readOnly: false
  storageClassName: jellyfin-data-nvme-sc
