apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-nvme-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/nvme/config"
    server: 192.168.68.71
    readOnly: false
  storageClassName: jellyfin-config-nvme-sc
