apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: jellyfin-data-nvme-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.68.71/mnt/nvme/data
    volumeAttributes:
      server: 192.168.68.71
      share: /mnt/nvme/data
#  nfs:
#    path: "/mnt/nvme/data"
#    server: 192.168.68.71
#    readOnly: false
  storageClassName: jellyfin-data-nvme-sc
