apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-jellyfin-data
provisioner: cluster.local/nfs-server-nfs-server-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
