apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-data
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/"
    server: 10.43.0.11
    readOnly: false
  storageClassName: nfs-jellyfin-data
