apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /config2
    server: 10.43.0.11
    readOnly: false
  storageClassName: nfs-jellyfin-config
