apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-data
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    server: nfs-server.nfs-server-nfs-server-provisioner.svc.cluster.local
    readOnly: false
  storageClassName: nfs-jellyfin-data
