apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /config
    server: nfs-server.nfs-server-nfs-server-provisioner.svc.cluster.local
    readOnly: false
  storageClassName: nfs-jellyfin-config
