apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /config
    server: <TBD full service name for internal NFS server>
    readOnly: false
  storageClassName: nfs-jellyfin-config
