apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-static-jellyfin-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/config/"
    server: 192.168.68.71
    readOnly: false
  storageClassName: nfs-jellyfin-config
