apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usb-pvc
  namespace: nfs-server
spec:
  storageClassName: usb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti # Should match or be less than the PV capacity
